version: '3'
services:
  spring_boot_com_mysql:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: spring_boot_com_mysql/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=spring_boot_mysql
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql